Docs
dlce-eva/dlce-eva pull request #1
Opened 2021-03-19 12:02 UTC by chrzyki

Still a lot of thinks that need to be added and that I want to add but it's a start, I hope.

2021-03-19 13:24 UTC, Bibiko requested changes

2021-03-19 13:24 UTC, Bibiko commented on doc/python.md
> +### OSX
I'd use the latest name `macOS` instead of OSX

2021-03-19 13:24 UTC, Bibiko commented on doc/python.md
> +
I'd add if using Python 3.x then one has to check as well whether `pip` is symlinked against `pip3`. Otherwise one should use `pip3` over `pip` or symlink it manually  -- and OSX -> macOS

2021-03-19 13:24 UTC, Bibiko commented on doc/shell.md
> +environments, e.g. Linux, OSX, and the Git bash in Windows.
OSX -> macOS

2021-03-19 13:24 UTC, Bibiko commented on doc/shell.md
> +
here I'd add that Windows users have to use the `Windows PowerShell`

2021-03-19 13:24 UTC, Bibiko commented on doc/git.md
> +  (`.DS_Store` folder in OSX, virtual environments, etc.)
OSX -> macOS

2021-03-19 13:24 UTC, Bibiko commented on doc/python.md
> +[brew](https://brew.sh/).
OSX -> macOS

2021-03-19 13:34 UTC, chrzyki commented
Thanks!

2021-03-19 13:54 UTC, johenglisch approved these changes

2021-03-21 14:58 UTC, chrzyki commented
I'll merge for now to have the stable links to the doc files. Happy to incorporate more changes in a second round of refinements.

2021-03-21 14:58 UTC, merged